### ISSUE TITLE
Clarification regarding nanopore data

### ISSUE THREAD

**Issue by lfaller** [sanger-pathogens/circlator#119]
Hi all,

I am interested in using Circlator to finish up a microbial assembly using nanopore data.

The section in the manual describing the input files seems to be geared towards Pacbio data.

`circlator all [options] <assembly.fasta> <reads.fasta> <output directory>`

For Nanopore data, is `reads.fasta` the file with the original nanopore reads? Or could these be illumina reads as well?

Thanks!
~Lina

**Comment by andrewjpage** [comment]
Yes you can use nanopore (not illumina) corrected reads as input. Dont use
the raw reads, instead use something like canu to generate corrected reads
and away you go.

If you have illumina and nanopore I would also suggest you try out
unicycler from Ryan Wick.

Andrew

On 6 Nov 2017 10:11 pm, "lfaller" <notifications@github.com> wrote:

Hi all,

I am interested in using Circlator to finish up a microbial assembly using
nanopore data.

The section in the manual describing the input files seems to be geared
towards Pacbio data.

circlator all [options] <assembly.fasta> <reads.fasta> <output directory>

For Nanopore data, is reads.fasta the file with the original nanopore
reads? Or could these be illumina reads as well?

Thanks!
~Lina

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sanger-pathogens/circlator/issues/119>, or mute the
thread

**Comment by lfaller** [comment]
Thanks for the feedback -- I will use the corrected reads from canu! I have also looked into unicycler and it seems to be performing very well the handful of different species I have tried it with!

Best,
~Lina
